### ISSUE TITLE
missing 1 required positional argument: 'doc'

### ISSUE THREAD

**Issue by suchdevnoskill** [scrazzz/dm-logger.py#1]
## Summary
Running `logger.py` gives an error I'm not familiar with/can't figure out how to fix ><

## Expected Results

Program to start after configuring Python environment and installing requirements..

## Actual Results
```shell
def TypeAlias(self, parameters):
TypeError: __init__() missing 1 required positional argument: 'doc'
```

## Info
Using Python 3.9.0
Not sure if I need like a config file....total noob...

**Comment by scrazzz** [comment]
Can you send the full trace back (with token and other important details removed) ?

**Comment by suchdevnoskill** [comment]
yeah ill get back to you with that a little later. Thanks for responding tho im sure its my lack of knowledge causing the error lol

**Comment by scrazzz** [comment]
Okay, I've made some changes to the code today. So make sure you use this latest one since the old one was missing an import.

**Comment by scrazzz** [comment]
Since I'm sure this error isn't with the script itself, I'm going to close this issue. You can always join the support server mentioned in the readme for help.
