### ISSUE TITLE
Bug not logging both message and attachment

### ISSUE THREAD

**Issue by raqtor1** [scrazzz/dm-logger.py#3]
## Summary
Messages with an attachment logs only attachment.

## Expected Results
Both message and attachments should be logged.

## Actual Results
Only the attachment is logged and message gets ignored.

## Info
- discord.py 1.6.0
- Python 3.8

**Comment by raqtor1** [comment]
Oh ok, I didn't see the project. Could this milestone be in the milestone section as well?

**Comment by scrazzz** [comment]
This isn't my main thing or whatever. I just do it in my free time. And I don't plan on supporting this script in the future since selfbot usability is going to be removed in future discord.py updates.

**Comment by raqtor1** [comment]
Shall I open a PR to fix this issue whenever I can?

**Comment by scrazzz** [comment]
> Shall I open a PR to fix this issue whenever I can?

Sure, go ahead.
